print('what is your favorite food?')
nounf = input()
print('what is your favorite number?')
num1 = int(input())
print('what is your least favorite number?')
num2 = int(input())
print(num1 + num2)
